# Generated by Django 2.1.7 on 2019-11-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='exam_type',
            new_name='exam_number',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_amount',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_sn',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('success', '成功'), ('closed', '未付款交易超时'), ('cancel', '取消'), ('finished', '结束'), ('unpaid', '待支付')], default='unpaid', help_text='订单状态', max_length=20, verbose_name='订单状态'),
        ),
    ]
