# Generated by Django 2.1.7 on 2019-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20191105_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(blank=True, default=123, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='支付'),
            preserve_default=False,
        ),
    ]
