# Generated by Django 2.2.6 on 2019-11-07 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0003_auto_20191106_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('IDCard', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.IntegerField(blank=True, default=0, verbose_name='考生序号')),
                ('exam_id', models.CharField(blank=True, help_text='考生号', max_length=20, null=True, verbose_name='考号')),
                ('class_number', models.IntegerField(blank=True, default=0, verbose_name='考场号')),
                ('exam_number', models.CharField(blank=True, default='', help_text='考试类型', max_length=20, verbose_name='考试类型')),
                ('grade', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
            },
        ),
    ]
