# Generated by Django 2.1.7 on 2019-11-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollmentSystem', '0002_auto_20191102_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pay_status',
        ),
    ]
