# Generated by Django 2.2.6 on 2019-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollmentSystem', '0002_auto_20191102_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pay_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
