# Generated by Django 2.2.6 on 2019-11-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollmentSystem', '0003_profile_pay_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ex_addr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='if_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
